### ISSUE TITLE
Updating from 1.1.0 to 1.2.0 causes the server to kick players

### ISSUE THREAD

**Issue by SplendidAlakey** [Emafire003/ColoredGlowLib#2]
**MC** 1.18.2
**Fabric API** 0.48.0
**ColoredGlowLib** 1.2.0

Not sure if these are the exact steps needed to reproduce the issue, but that's what caused it for me:

1. Install version 1.1.0 and run the server
2. Stop the server, update to 1.2.0 and run again
3. Upon joining the world, I ran around for a few seconds, fell of a few blocks to reduce my saturation, ate a glowberry and got kicked from the server after 2-3sec
4. Trying to join back causes an immediate disconnect with nothing useful in the server console (simply says player disconnected and failed to read packet upon rejoining)

Reverting back to 1.1.0 let me join and no issues happen no matter what I do.

I could post a full log, however it's 11k lines long and I believe only the following lines matter for the issue (as they are the only ones referencing your mod): https://gist.github.com/Footage2-Amply-Pounce/822dc316052bb7c9a4fc78a503e15c8a

**Comment by Emafire003** [comment]
Ah. Try to delete the coloredglowlibdata.json from the config folder. That's probably it. Oh and both from the server and the client. If you need to keep some entities with a custom glow copy the stuff after first line and paste in the same place in the new file. Aka under the first line. Btw, why the glowberry? Using FoxGlow?

P.S. if it doesn't work send the full log if you can

**Comment by SplendidAlakey** [comment]
Deleted the config from both the client and the server, this time the logs showed only 1 issue: https://gist.github.com/Footage2-Amply-Pounce/b549fe1ce3a62d8de8795cf980282fbe

I ran around again, ate a glowberry and got kicked right after the glow effect wore off. I could join back, but got kicked a few seconds later without doing anything.

Yes, completely forgot to mention, I am using FoxGlow and figured eating a glowberry after updating would be a good way to test if things work.

**Comment by Emafire003** [comment]
Ah yes that's it. Remove foxglow for now, it includes coloredglowlib already (probably not going to do so in the near future to prevent problems like this) and I haven't updated it yet. Or just remove coloredglowlib for now. Btw yes, it's a good way of testing it xD

**Comment by Emafire003** [comment]
Uh wait no I still don't really know why you got kicked. Can you send the full log? Or at least the part where you got kicked and a bit of stuff before that?

**Comment by SplendidAlakey** [comment]
Ah, makes sense. I'll just keep the FoxGlow for now and remove CGL.

> Uh wait no I still don't really know why you got kicked. Can you send the full log? Or at least the part where you got kicked and a bit of stuff before that?

Yep, there you go: https://gist.github.com/Footage2-Amply-Pounce/51ef124b36c66f7785ca6e6ac37ce534

The only reason I didn't want to include it was because its absurdly long due to a mod I have (vertical slabs) that keeps listing every single block it can't load due to the fact that I simply don't use mods that add those blocks. In fact the log is so big, this is the first time my github gist got truncated.

Should I close the issue since nothing seems to be broken, it's just that I shouldn't use CGL 1.2.0 with FoxGlow for now?

**Comment by Emafire003** [comment]
Could you send the client's log? It's in the %appdata% under logs. If you have nerver restarted minecraft after the first time you got kicked, send the latest.log, if not send the log of when you have been kicked. (I suspects it complains because the same mod is being run on two version but still). Ah, i've also published FoxGlow 1.2.4 now

**Comment by SplendidAlakey** [comment]
Here you go, this is the log from an hour ago after I got kicked and submitted the issue: https://gist.github.com/Footage2-Amply-Pounce/255168964b2b65cf7bd2aa84a27aa147

**Comment by Emafire003** [comment]
Uhm ok, it appears a packet has arrived and has been recived but it was empty and i didn't check what happens in that case. Try to use the new version of foxglow, but i think the error will remain. I don't know if i will be able to fixit before tomorrow at best or maybe monday :/

**Comment by SplendidAlakey** [comment]
Yep, just tried FoxGlow 1.2.4 and CGL 1.2.0 together, still getting kicked and producing the same exact logs.

> I don't know if i will be able to fixit before tomorrow at best or maybe monday :/

No problem, take your time, I'll just keep using the previous version for now :)

**Comment by Emafire003** [comment]
do me a favor and try to use this version https://modrinth.com/mod/coloredglowlib/version/1.2.1

**Comment by SplendidAlakey** [comment]
> do me a favor and try to use this version https://modrinth.com/mod/coloredglowlib/version/1.2.1

Tried with FoxGlow 1.2.4NOLIB, same issue: https://gist.github.com/Footage2-Amply-Pounce/a37f3a23b807612affc8dba537f8e1a9

**Comment by Emafire003** [comment]
Welp. That's kind of a problem then. I'll have to look into it :/

**Comment by Emafire003** [comment]
Check the new version on modrinth, it should work now. I've tested it with foxglow too and it seems fine. (nolib version, which i am going to update anyway in a bit maybe. I'll updated it on modrinth at least) (delete the config again please)

**Comment by SplendidAlakey** [comment]
Yep, now everything works as intended. Thanks!
